#!/usr/bin/env sh 

# create must exist directories
mkdir -p /etc/s6/init/env-stage2
mkdir -p /etc/{cont-init.d,cont-finish.d,fix-attrs.d,services.d}

# create "supervise" directory in fdholder, its needed for no-catchall
# stage2 wake up
mkdir -p /etc/s6/services/s6-fdholderd/supervise
chmod 0700 /etc/s6/services/s6-fdholderd/supervise

# fix perms for utilities
chmod 0755 /usr/bin/fix-attrs
chmod 0755 /usr/bin/logutil-{newfifo,service,service-main}
chmod 0755 /usr/bin/printcontenv
chmod 0755 /usr/bin/with-{contenv,retries}

# fix init perms
chmod 0755 /init
chmod 0755 /etc/s6/init/init-*
chmod 0755 /etc/s6/init-catchall/init-*
chmod 0755 /etc/s6/init-no-catchall/init-*
chmod 0755 /etc/s6/services/.s6-svscan/{crash,finish}
chmod 0755 /etc/s6/services/s6-fdholderd/run
chmod 0755 /etc/s6/services/s6-svscan-log/run
